### ISSUE TITLE
Test fail

### ISSUE THREAD

**Issue by pditommaso** [jexler/grengine#2]
The following test fail: 
    
    ch.grengine.code.DefaultSingleSourceCodeTest > testConstructPlusGetters FAILED
        org.junit.ComparisonFailure at DefaultSingleSourceCodeTest.java:125

Tested with: 

    Gradle 2.2.1
    java version "1.8.0_40"

**Comment by jexler** [comment]
Bug in unit test only (assumed order of compiled classes in set of compiled class names), occurs apparently usually if using Java 8 to run tests, as compared to Java 6 or 7; Groovy version etc. seem not to matter.

Fixed: eb3aa25dc3e
